# Generated by Django 3.1.7 on 2021-04-30 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Password', models.CharField(max_length=20)),
                ('Confirm', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('ParNo', models.CharField(max_length=12)),
                ('Std', models.CharField(max_length=5)),
                ('Address', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Tinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Password', models.CharField(max_length=20)),
                ('Confirm', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('PhoneNo', models.CharField(max_length=12)),
                ('Address', models.CharField(max_length=1000)),
            ],
        ),
    ]
