# Generated by Django 3.1.7 on 2021-04-30 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngoapp', '0002_auto_20210430_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tinfo',
            name='Email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
