# Generated by Django 3.1.7 on 2021-05-01 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngoapp', '0003_auto_20210430_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sinfo',
            name='Address',
        ),
    ]
